#!/bin/bash

set -e

echo $(date -Isec) "Extracting latest nodelist from filearea"
unzip -joLqq /ftn/var/filebox/nodelist/NODELIST.ZIP -d /ftn/var/nodelist/fullsrc
echo $(date -Isec) "Updating nodelist with nodediff"
nlupd
echo $(date -Isec) "Compiling nodelist for GoldEd"
gnlnx
echo $(date -Isec) "Completed successfully"
