#!/bin/bash

set -e

echo $(date -Isec) "Extracting latest nodelist from filearea"
unzip -joLqq /ftn/var/file/base/nodelist/NODELIST.ZIP -d /ftn/var/nodelist/orig
echo $(date -Isec) "Updating nodelist with nodediff"
nlupd
echo $(date -Isec) "Compiling nodelist for GoldEd"
goldnode -c /ftn/.golded/golded.cfg
echo $(date -Isec) "Completed successfully"
