#!/bin/bash

set -e

echo $(date -Isec) "Scanning for inbound messages and files"
hpt scan && sync
echo $(date -Isec) "Packing FIDO messages and files"
hpt pack && sync
poll
echo $(date -Isec) "Tossing received messages"
hpt toss && sync
echo $(date -Isec) "Tossing received files"
htick toss && sync
echo $(date -Isec) "Annoncing received files"
htick announce && sync
echo $(date -Isec) "Linking received messages into echo areas"
hpt link && sync
echo $(date -Isec) "AreaFix changing requests processing"
hpt afix && sync
echo $(date -Isec) "FileFix changing requests processing"
htick ffix && sync
echo $(date -Isec) "New fecho files tossing"
htick toss && sync
echo $(date -Isec) "Completed successfully"
